#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

python -m githooks.linter --warn -minimum 10
if [ $? -ne 0 ]
then
  echo "The pylint rating did not meet expected values."
  exit 1
fi